### ISSUE TITLE
Home page for the listings

### ISSUE THREAD

**Issue by mvgame74** [BecaLParker/Cloud-stay#10]
Client->Controller: "post user sign up / sign in information"
Controller->Model: "post user information"
Model->Controller: "return whether user is authenticated"
Controller->View: "request the home page"
View->Controller: "post home page"
Controller->Client: "Display the home page"

**Comment by BecaLParker** [comment]
:relieved: On Tuesday we got the skeleton of this tested and implemented with hard coded listings. 

:building_construction: **What still needs doing:** On Wednesday, whoever takes this ticket, please test and implement integration with @Dev-ops-true Dev's listings database (clouds table). 

:warning: @mvgame74 and I have started writing the tests for this on branch: https://github.com/BecaLParker/Cloud-stay/tree/integrating_clouds_database so I'd suggest checkout and git pull that branch first.
